In [4]:
import numpy as np
import pandas as pd

In [5]:
np.random.seed(29)


### 1. How likely is it that you roll doubles when rolling two dice?

In [6]:
#first, create an array representing 1,000,000 rolls of 2 dice
n_trials = nrows = 100_000
n_dice = ncols = 2
#here's your "roll": there are six possibilities
rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [5, 6],
       [5, 5],
       [6, 5]])

In [7]:
rolls.shape

(100000, 2)

In [8]:
#get it in a DF
rolls = pd.DataFrame(rolls, columns=['first_roll','second_roll'])
rolls.head()

first_roll  second_roll
0           6            4
1           5            6
2           3            1
3           1            2
4           2            1

In [9]:
#in this example, i've created a function to count when they are the same
def count_doubles(row):
    return row.first_roll == row.second_roll
count_doubles
#and here, i create a new column full of booleans for when they are the same
rolls['doubles_count'] = rolls.apply(count_doubles, axis=1)
rolls.sample(20)

#or 
#df.apply(lambda row: row.values[0]==row.values[1],axis=1).mean()

first_roll  second_roll  doubles_count
78173           1            2          False
51121           1            3          False
60356           4            3          False
24304           2            4          False
77590           6            5          False
24491           6            3          False
11290           4            2          False
30277           4            5          False
56875           2            6          False
76125           5            4          False
30266           3            2          False
74481           2            6          False
25534           6            4          False
39360           5            4          False
98654           4            1          False
21040           4            4           True
94245           3            5          False
64548           4            5          False
98152           5            4          False
64276           1            2          False

In [10]:
#finally, get the average of where the two are the same
(rolls.doubles_count==True).mean()

0.16645

# classroom answer

In [11]:
#compare to github

In [12]:
rolls.apply(lambda row: row.values[0]==row.values[1],axis=1).mean()

0.16645

In [13]:
rolls.apply(lambda row: row[0]==row[1],axis=1).mean()

0.16645

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [14]:
n_trials = 100_000
n_coins = 8
#similar to above ex, but here we're just using a true/false choice and avoiding having to reshape
flips = np.random.choice([0,1], size=(n_trials, n_coins))
flips

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 1, 0]])

In [15]:
flips.shape

(100000, 8)

In [16]:
flips = pd.DataFrame(flips)
flips.sample(10)

0  1  2  3  4  5  6  7
30567  1  1  1  0  1  0  0  1
98537  0  0  1  0  1  1  1  0
54774  1  1  1  0  1  1  1  0
75432  1  1  0  0  1  0  0  1
75058  1  1  1  0  1  0  1  1
24667  0  1  0  1  0  0  1  1
66897  1  0  0  1  0  1  1  1
77787  0  0  0  1  1  0  1  1
36464  1  1  0  0  1  0  1  0
43005  1  1  0  1  1  1  0  0

In [17]:
#add a counter for the number of heads in our series
flips['n_heads'] = flips.sum(axis=1)
flips.sample(10)

0  1  2  3  4  5  6  7  n_heads
68862  0  0  1  1  0  1  0  0        3
45968  1  0  0  0  0  0  1  0        2
11275  1  0  1  0  1  1  1  1        6
37370  0  1  0  1  0  1  0  1        4
24146  1  0  0  0  0  0  1  1        3
92690  0  0  1  1  0  0  0  1        3
37675  1  0  1  1  1  0  0  0        4
2877   0  0  0  0  0  0  1  1        2
600    1  0  1  0  0  1  1  0        4
92170  0  1  1  0  1  0  0  0        3

In [18]:
#and get the average
(flips.n_heads == 3).mean()

0.22002

In [19]:
(flips.n_heads > 3).mean()

0.63437

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [20]:
n_trials = 100_000
n_billboards = 2

#get our array.  4 choices here; we'll say that '3' == ds student

billboards = np.random.choice([0,1,2,3], size=(n_trials, n_billboards))
billboards

array([[2, 3],
       [1, 3],
       [3, 1],
       ...,
       [1, 2],
       [0, 1],
       [0, 3]])

In [21]:
billboards = pd.DataFrame(billboards, columns=['first_bb','second_bb'])
billboards.head()

first_bb  second_bb
0         2          3
1         1          3
2         3          1
3         2          3
4         2          3

In [22]:
#add a row that returns a boolean if both billboards were a '3'
billboards['ds_count'] = (billboards.first_bb == 3) & (billboards.second_bb == 3)
billboards.sample(10)

first_bb  second_bb  ds_count
7581          0          0     False
3051          1          0     False
47169         1          0     False
49038         3          0     False
61885         0          1     False
62591         0          0     False
11777         0          2     False
74768         1          1     False
6609          2          3     False
30918         2          1     False

In [23]:
#and the average of ds_count == true (meaning both were ds students)
billboards.ds_count.mean()

0.06393

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [24]:
#here, we use np.random.normal to get our array, which is 5 (for 5 days) long, each value representing
#how many poptarts were bought that day.
nrows=100000
ncols=5
mu, sigma = 3, 1.5
# s = np.random.normal(mu,sigma,size = (100_000,5))
# s

s = np.random.normal(mu,sigma,nrows*ncols).astype(int).reshape(nrows,ncols)
#johns df was all integers and resulted in a higher % than mine

In [25]:
#where the sum of them is less than 17 means there should be some left

(s.sum(axis=1) < 17).mean()

0.8801

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [26]:
#johns idea:
# df=pd.DataFrame({'men': men,
#                 'women': women})

In [27]:
#similarly: 100_000 samples, but only 1 in each array
mu, sigma = 178, 8
men = np.random.normal(mu,sigma,size = (100_000,1))
men = pd.DataFrame(men)
men

0
0      171.044245
1      181.376416
2      162.941701
3      171.106076
4      180.012564
...           ...
99995  169.782460
99996  185.887316
99997  176.533812
99998  180.536371
99999  173.474082

[100000 rows x 1 columns]

In [28]:
mu, sigma = 170, 6
women = np.random.normal(mu,sigma,size = (100_000,1))
women = pd.DataFrame(women)
women

0
0      167.754212
1      180.562796
2      168.464675
3      175.074747
4      160.927437
...           ...
99995  170.587884
99996  163.278856
99997  172.101643
99998  176.059054
99999  173.819420

[100000 rows x 1 columns]

In [29]:
#since the arrays are identical, we can do a direct comparison
#see john's code above to jam them in the same DF
(women > men).mean()

0    0.21034
dtype: float64

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?


In [30]:
n_trials = 100_000
n_installs = 50
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [31]:
installs = pd.DataFrame(installs)
installs

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
0       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
1       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
2       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
3       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
4       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
99995   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99996   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99997   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99998   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99999   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   

       46  47  48  49  
0       1   1   1   1  
1       1   1   1   1  
2       1   1   1   1  
3       1   1   1   1  
4       1   1   1   1  
...    ..  ..  ..  ..  
99995   1   1   1   1  
99996   1   1   1   1  
99997   1   1   1   1  
99998   1   1   1   1  
99999   1   1   1   1  

[100000 rows x 50 columns]

In [32]:
#get a count of how many times all the installs were fine; 50 means they were all good
installs['count'] = installs.sum(axis=1)
installs.sample(10)

0  1  2  3  4  5  6  7  8  9  ...  41  42  43  44  45  46  47  48  49  \
97163  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
48095  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
97687  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
51786  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
93359  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
20530  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
90273  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
36481  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
30086  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
68376  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   0   

       count  
97163     50  
48095     50  
97687     50  
51786     50  
93359     50  
20530     49  
90273     49  
36481     50  
30086     50  
68376     49  

[10 rows x 51 columns]

In [33]:
#the average of where the count was exactly 50, meaning all installs were good

(installs['count'] == 50).mean()

0.81843

In [34]:
#for 100 students:

n_trials = 100_000
n_installs = 100
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] == 100).mean()



#this particular answer looks like it came out wrong. the rest seem ok

0.67212


### What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [35]:
#for 150 students:
n_trials = 100_000
n_installs = 150
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] != 150).mean()

0.45338

### How likely is it that 450 students all download anaconda without an issue?

In [36]:
#for 450  students:
n_trials = 100_000
n_installs = 450
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] == 450).mean()

0.16429

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [37]:
n_trials = 100_000
n_days = 3
#0 = no food trucks; 1=yes food trucks
food_truck = np.random.choice([0,1], size=(n_trials, n_days), p=(.3,.7))
food_truck = pd.DataFrame(food_truck)
food_truck.sample(10)
#below, then, is our sample of food truck presence on 3 consecutive days

0  1  2
46402  0  1  1
63244  1  0  1
79174  1  0  1
13543  1  1  0
37864  1  0  1
60791  1  1  1
17570  0  1  1
20363  1  1  1
56937  0  0  1
1738   1  1  1

In [38]:
food_truck['ft_count'] = food_truck.sum(axis=1)
food_truck

0  1  2  ft_count
0      0  0  0         0
1      0  1  1         2
2      1  0  1         2
3      1  1  1         3
4      0  1  1         2
...   .. .. ..       ...
99995  0  1  0         1
99996  0  0  1         1
99997  1  0  1         2
99998  1  0  1         2
99999  0  1  1         2

[100000 rows x 4 columns]

In [39]:
#here's our likelyhood of having no food trucks in 3 consecutive days:
(food_truck.ft_count == 0).mean()

0.02673

### How likely is it that a food truck will show up sometime this week?

In [40]:
n_trials = 100_000
n_days = 7
#0 = no food trucks; 1=yes food trucks
food_truck = np.random.choice([0,1], size=(n_trials, n_days), p=(.3,.7))
food_truck = pd.DataFrame(food_truck)
food_truck['ft_count'] = food_truck.sum(axis=1)
food_truck.sample(10)

#below, then, is our sample of food truck presence on 7 consecutive days

0  1  2  3  4  5  6  ft_count
37973  1  1  1  0  1  1  0         5
84984  1  0  1  1  1  1  1         6
94373  1  1  1  1  0  1  1         6
10108  0  1  0  1  1  1  1         5
47614  1  1  1  1  1  1  1         7
27088  1  1  1  1  1  0  1         6
37767  0  1  1  0  1  0  1         4
2834   0  1  1  1  1  1  1         6
73849  0  1  1  0  1  1  1         5
73326  1  0  0  1  1  1  1         5

In [41]:
#here's our likelyhood of having a food truck on 1 day this week:
(food_truck.ft_count != 0).mean()

0.99971

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [62]:
from math import comb

comb(23,2)

253

In [63]:
n_trials = 100_000
n_bdays = 23
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(113/366,(253/366))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
birthday.sample(10)

SyntaxError: invalid syntax (<ipython-input-63-bf8283cf7a03>, line 5)

In [64]:
366-253

113

In [56]:
(birthday.bd_count > 0).mean()

0.99975

### What if it's 20 people? 40?

In [44]:
n_trials = 100_000
n_bdays = 20
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(364/365,1/365))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
(birthday.bd_count > 0).mean()

0.0531

In [45]:
n_trials = 100_000
n_bdays = 40
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(364/365,1/365))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
(birthday.bd_count > 0).mean()

0.10556

# JOHN'S ANSWER, SINCE MINE IS INCORRECT

In [51]:
def shared_birthday(people):

    nrows = 100_000 # set rows to number of simulations
    ncols = people  # set columns to number of people in each simulation

    # create array with each value representing the numbered day of the year that person was born on. (This ignores leap years)
    # reshape the aray into trial groups
    sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Add boolian column to df showing weather there are less unique numbers in each row (trial) than there are total columns
    df['matching_birthdays'] = df.nunique(axis=1) < ncols

    # get mean of calculation True/False columns
    # format and print results
    matching_birthdays = df['matching_birthdays'].mean()

    # print result
    print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {round(matching_birthdays*100)}%')

In [47]:
num_list = [23, 20, 40]

for num in num_list:
    shared_birthday(num)

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 40 people having at least two people that share a birthday are 89%
