In [42]:
import numpy as np
import pandas as pd

In [43]:
np.random.seed(29)


### 1. How likely is it that you roll doubles when rolling two dice?

In [207]:
#first, create an array representing 1,000,000 rolls of 2 dice
n_trials = nrows = 100_000
n_dice = ncols = 2
#here's your "roll": there are six possibilities
rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[1, 2],
       [1, 5],
       [5, 3],
       ...,
       [4, 1],
       [6, 4],
       [1, 2]])

In [208]:
rolls.shape

(100000, 2)

In [209]:
#get it in a DF
rolls = pd.DataFrame(rolls, columns=['first_roll','second_roll'])
rolls.head()

first_roll  second_roll
0           1            2
1           1            5
2           5            3
3           6            1
4           2            2

In [210]:
#in this example, i've created a function to count when they are the same
def count_doubles(row):
    return row.first_roll == row.second_roll
count_doubles
#and here, i create a new column full of booleans for when they are the same
rolls['doubles_count'] = rolls.apply(count_doubles, axis=1)
rolls.sample(20)

#or 
#df.apply(lambda row: row.values[0]==row.values[1],axis=1).mean()

first_roll  second_roll  doubles_count
20024           4            6          False
89936           4            2          False
25452           5            1          False
41652           4            1          False
75363           1            6          False
99462           2            6          False
64425           1            6          False
3193            4            4           True
32941           3            5          False
78213           4            5          False
42156           1            2          False
48601           3            5          False
73455           1            4          False
29702           2            4          False
12795           5            3          False
15874           1            2          False
84415           4            5          False
90865           1            1           True
82270           2            6          False
1590            4            3          False

In [211]:
#finally, get the average of where the two are the same
(rolls.doubles_count==True).mean()

0.16491

# classroom answer

In [242]:
#compare to github

In [243]:
rolls.apply(lambda row: row.values[0]==row.values[1],axis=1).mean()

0.16491

In [244]:
rolls.apply(lambda row: row[0]==row[1],axis=1).mean()

0.16491

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [212]:
n_trials = 100_000
n_coins = 8
#similar to above ex, but here we're just using a true/false choice and avoiding having to reshape
flips = np.random.choice([0,1], size=(n_trials, n_coins))
flips

array([[0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 0, 0]])

In [213]:
flips.shape

(100000, 8)

In [214]:
flips = pd.DataFrame(flips)
flips.sample(10)

0  1  2  3  4  5  6  7
89562  1  1  1  0  0  0  0  0
61140  0  0  0  0  0  0  0  0
94455  1  1  1  1  0  0  1  1
53689  1  1  1  0  0  0  1  0
97822  1  0  1  0  0  1  1  1
65114  0  1  1  0  0  1  1  0
39094  1  0  0  0  1  0  1  1
44914  0  0  0  1  0  0  0  1
7808   1  1  1  1  0  1  1  0
93893  0  0  1  0  0  0  0  1

In [215]:
#add a counter for the number of heads in our series
flips['n_heads'] = flips.sum(axis=1)
flips.sample(10)

0  1  2  3  4  5  6  7  n_heads
95837  0  1  0  0  0  1  1  1        4
62290  1  1  1  1  1  1  1  1        8
9545   1  0  1  0  0  1  1  1        5
81559  0  1  0  0  1  0  1  0        3
34148  0  1  0  1  1  1  1  0        5
1517   1  1  0  0  1  1  1  1        6
95418  0  1  0  1  1  0  1  0        4
87372  1  1  1  1  1  0  1  1        7
86221  0  0  1  0  0  0  0  0        1
763    0  1  1  1  1  0  0  0        4

In [216]:
#and get the average
(flips.n_heads == 3).mean()

0.21711

In [248]:
(flips.n_heads > 3).mean()

0.63953

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [217]:
n_trials = 100_000
n_billboards = 2

#get our array.  4 choices here; we'll say that '3' == ds student

billboards = np.random.choice([0,1,2,3], size=(n_trials, n_billboards))
billboards

array([[2, 3],
       [1, 1],
       [2, 0],
       ...,
       [0, 1],
       [0, 2],
       [2, 1]])

In [218]:
billboards = pd.DataFrame(billboards, columns=['first_bb','second_bb'])
billboards.head()

first_bb  second_bb
0         2          3
1         1          1
2         2          0
3         1          2
4         0          2

In [219]:
#add a row that returns a boolean if both billboards were a '3'
billboards['ds_count'] = (billboards.first_bb == 3) & (billboards.second_bb == 3)
billboards.sample(10)

first_bb  second_bb  ds_count
47834         3          0     False
6350          1          2     False
25021         3          2     False
93819         2          2     False
24798         2          1     False
55702         1          2     False
6354          2          1     False
58472         2          0     False
81004         2          2     False
57733         2          3     False

In [220]:
#and the average of ds_count == true (meaning both were ds students)
billboards.ds_count.mean()

0.06148

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [249]:
#here, we use np.random.normal to get our array, which is 5 (for 5 days) long, each value representing
#how many poptarts were bought that day.
nrows=100000
ncols=5
mu, sigma = 3, 1.5
# s = np.random.normal(mu,sigma,size = (100_000,5))
# s

s = np.random.normal(mu,sigma,nrows*ncols).astype(int).reshape(nrows,ncols)
#johns df was all integers and resulted in a higher % than mine

In [250]:
#where the sum of them is less than 17 means there should be some left

(s.sum(axis=1) < 17).mean()

0.87773

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [ ]:
#johns idea:
# df=pd.DataFrame({'men': men,
#                 'women': women})

In [223]:
#similarly: 100_000 samples, but only 1 in each array
mu, sigma = 178, 8
men = np.random.normal(mu,sigma,size = (100_000,1))
men = pd.DataFrame(men)
men

0
0      188.213021
1      165.893246
2      192.133405
3      169.407950
4      165.737822
...           ...
99995  182.880710
99996  192.943671
99997  181.811884
99998  171.520532
99999  187.503157

[100000 rows x 1 columns]

In [224]:
mu, sigma = 170, 6
women = np.random.normal(mu,sigma,size = (100_000,1))
women = pd.DataFrame(women)
women

0
0      173.735546
1      172.128925
2      178.399248
3      165.562648
4      179.497412
...           ...
99995  174.901489
99996  173.830622
99997  173.614269
99998  178.157819
99999  178.490321

[100000 rows x 1 columns]

In [225]:
#since the arrays are identical, we can do a direct comparison
#see john's code above to jam them in the same DF
(women > men).mean()

0    0.20849
dtype: float64

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?


In [226]:
n_trials = 100_000
n_installs = 50
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [227]:
installs = pd.DataFrame(installs)
installs

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
0       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
1       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
2       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
3       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
4       1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
99995   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99996   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99997   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   
99998   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   0   1   1   
99999   0   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   

       46  47  48  49  
0       1   1   1   1  
1       1   1   1   1  
2       1   1   1   1  
3       1   1   1   1  
4       1   1   1   1  
...    ..  ..  ..  ..  
99995   1   1   1   1  
99996   1   1   1   1  
99997   1   1   1   1  
99998   1   1   1   1  
99999   1   1   1   1  

[100000 rows x 50 columns]

In [228]:
#get a count of how many times all the installs were fine; 50 means they were all good
installs['count'] = installs.sum(axis=1)
installs.sample(10)

0  1  2  3  4  5  6  7  8  9  ...  41  42  43  44  45  46  47  48  49  \
3972   1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
14106  1  1  1  1  1  1  1  0  0  1  ...   1   1   1   1   1   1   1   1   1   
11433  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
79520  1  1  1  1  1  1  1  1  1  1  ...   0   1   1   1   1   1   1   1   1   
58225  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
32171  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
99110  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
80025  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
20265  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
23840  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   

       count  
3972      49  
14106     48  
11433     50  
79520     49  
58225     50  
32171     50  
99110     50  
80025     50  
20265     50  
23840     50  

[10 rows x 51 columns]

In [229]:
#the average of where the count was exactly 50, meaning all installs were good

(installs['count'] == 50).mean()

0.8186

In [230]:
#for 100 students:

n_trials = 100_000
n_installs = 100
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] == 100).mean()



#this particular answer looks like it came out wrong. the rest seem ok

0.66784


### What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [231]:
#for 150 students:
n_trials = 100_000
n_installs = 150
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] != 150).mean()

0.45208

### How likely is it that 450 students all download anaconda without an issue?

In [232]:
#for 450  students:
n_trials = 100_000
n_installs = 450
#0 == fails, 1 == succeeds
installs = np.random.choice([0,1], size=(n_trials, n_installs), p=(1/250,249/250))
installs = pd.DataFrame(installs)
installs['count'] = installs.sum(axis=1)

(installs['count'] == 450).mean()

0.16522

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [233]:
n_trials = 100_000
n_days = 3
#0 = no food trucks; 1=yes food trucks
food_truck = np.random.choice([0,1], size=(n_trials, n_days), p=(.3,.7))
food_truck = pd.DataFrame(food_truck)
food_truck.sample(10)
#below, then, is our sample of food truck presence on 3 consecutive days

0  1  2
83591  0  1  1
18994  1  1  1
13910  1  0  0
1503   0  1  1
75893  1  0  1
91472  1  0  1
28595  0  1  0
54761  0  1  1
23653  1  1  1
9479   1  1  1

In [234]:
food_truck['ft_count'] = food_truck.sum(axis=1)
food_truck

0  1  2  ft_count
0      1  1  1         3
1      1  1  1         3
2      0  1  0         1
3      1  1  0         2
4      1  1  1         3
...   .. .. ..       ...
99995  1  1  1         3
99996  1  1  1         3
99997  0  1  1         2
99998  1  1  1         3
99999  1  0  1         2

[100000 rows x 4 columns]

In [235]:
#here's our likelyhood of having no food trucks in 3 consecutive days:
(food_truck.ft_count == 0).mean()

0.02679

### How likely is it that a food truck will show up sometime this week?

In [236]:
n_trials = 100_000
n_days = 7
#0 = no food trucks; 1=yes food trucks
food_truck = np.random.choice([0,1], size=(n_trials, n_days), p=(.3,.7))
food_truck = pd.DataFrame(food_truck)
food_truck['ft_count'] = food_truck.sum(axis=1)
food_truck.sample(10)

#below, then, is our sample of food truck presence on 7 consecutive days

0  1  2  3  4  5  6  ft_count
62902  1  1  1  0  1  1  1         6
64008  0  1  1  0  1  1  0         4
75611  1  1  1  1  1  1  1         7
35948  1  1  0  1  0  1  1         5
53376  1  1  1  1  1  1  0         6
322    0  1  1  1  1  1  1         6
13158  0  0  1  0  0  0  0         1
13850  0  1  1  0  1  1  1         5
57709  1  1  1  1  1  0  1         6
45493  1  0  0  1  1  1  1         5

In [237]:
#here's our likelyhood of having a food truck on 1 day this week:
(food_truck.ft_count != 0).mean()

0.99968

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [238]:
n_trials = 100_000
n_bdays = 23
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(364/365,1/365))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
birthday.sample(10)

0  1  2  3  4  5  6  7  8  9  ...  14  15  16  17  18  19  20  21  22  \
37684  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
67539  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
10946  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2939   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
9510   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
6141   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
32891  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
66897  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
36901  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
62098  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   

       bd_count  
37684         0  
67539         0  
10946         0  
2939          0  
9510          0  
6141          0  
32891         0  
66897         0  
36901         0  
62098         0  

[10 rows x 24 columns]

In [239]:
(birthday.bd_count > 0).mean()

0.06054

### What if it's 20 people? 40?

In [240]:
n_trials = 100_000
n_bdays = 20
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(364/365,1/365))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
(birthday.bd_count > 0).mean()

0.05276

In [241]:
n_trials = 100_000
n_bdays = 40
#0 = don't share bday, 1= share bday
birthday = np.random.choice([0,1], size=(n_trials, n_bdays), p=(364/365,1/365))
birthday = pd.DataFrame(birthday)
birthday['bd_count'] = birthday.sum(axis=1)
(birthday.bd_count > 0).mean()

0.10547