In [42]:
import numpy as np
import pandas as pd

In [43]:
np.random.seed(29)

### 1. How likely is it that you roll doubles when rolling two dice?

In [44]:
n_trials = nrows = 1_000_000
n_dice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [4, 4],
       [5, 3],
       [4, 2]])

In [45]:
rolls.shape

(1000000, 2)

In [46]:
rolls = pd.DataFrame(rolls, columns=['first_roll','second_roll'])
rolls.head()

first_roll  second_roll
0           6            4
1           5            6
2           3            1
3           1            2
4           2            1

In [47]:
def count_doubles(row):
    return row.first_roll == row.second_roll
count_doubles
rolls['doubles_count'] = rolls.apply(count_doubles, axis=1)
rolls.sample(20)

first_roll  second_roll  doubles_count
731639           5            5           True
638494           3            5          False
205898           2            6          False
328909           4            5          False
165299           4            5          False
433413           2            4          False
292370           6            4          False
18811            6            3          False
750288           6            2          False
50665            3            6          False
489898           2            5          False
281570           5            6          False
680184           6            1          False
2731             3            3           True
4576             4            4           True
483481           1            6          False
560946           6            6           True
698912           6            6           True
529342           2            5          False
953264           1            4          False

In [48]:
(rolls.doubles_count==True).mean()

0.166917

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [58]:
n_trials = 100_000
n_coins = 8

flips = np.random.choice([0,1], size=(n_trials, n_coins))
flips

array([[0, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 1, 0]])

In [59]:
flips.shape

(100000, 8)

In [60]:
flips = pd.DataFrame(flips)
flips.sample(10)

0  1  2  3  4  5  6  7
90018  0  0  0  0  0  1  0  1
58825  0  1  1  1  0  1  1  1
41789  0  1  0  0  0  1  1  0
17054  1  0  0  0  0  1  1  1
69216  1  0  1  0  0  1  1  0
32472  1  0  1  1  0  0  1  0
6709   0  0  0  1  1  1  0  1
31932  0  0  1  1  1  0  1  0
59519  0  0  1  1  1  0  1  1
95190  1  1  0  1  1  1  1  1

In [61]:
flips['n_heads'] = flips.sum(axis=1)
flips.sample(10)

0  1  2  3  4  5  6  7  n_heads
49026  0  1  1  0  0  1  1  1        5
4915   0  1  0  0  0  1  1  0        3
12579  0  0  0  1  0  0  1  0        2
66768  1  1  0  0  1  0  0  0        3
75506  1  0  1  0  0  1  0  0        3
28259  1  1  0  0  0  0  1  1        4
10736  1  1  1  1  0  0  1  1        6
68503  0  1  1  1  0  1  1  0        5
65850  0  0  0  0  1  1  0  0        2
66497  0  0  1  0  1  0  1  1        4

In [62]:
(flips.n_heads == 3).mean()

0.21724

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [66]:
n_trials = 100_000
n_billboards = 2

billboards = np.random.choice([0,1,2,3], size=(n_trials, n_billboards))
billboards

array([[0, 3],
       [3, 2],
       [2, 0],
       ...,
       [2, 0],
       [3, 3],
       [2, 0]])

In [68]:
billboards = pd.DataFrame(billboards, columns=['first_bb','second_bb'])
billboards.head()

first_bb  second_bb
0         0          3
1         3          2
2         2          0
3         2          1
4         3          0

In [69]:
billboards['ds_count'] = (billboards.first_bb == 3) & (billboards.second_bb == 3)
billboards.sample(10)

first_bb  second_bb  ds_count
50278         1          1     False
7220          1          3     False
11735         2          0     False
82565         2          1     False
9364          1          3     False
8070          2          2     False
92730         0          2     False
97356         3          0     False
81418         3          1     False
53666         3          3      True

In [70]:
billboards.ds_count.mean()

0.06265

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [105]:
mu, sigma = 3, 1.5
s = np.random.normal(mu,sigma,size = (100_000,5))
s

array([[2.31498356, 3.80299243, 4.04693461, 1.31504636, 4.83958929],
       [2.58405653, 4.00942842, 1.7295788 , 1.66791707, 1.42272179],
       [2.10188089, 3.23729999, 2.46168407, 1.68633274, 3.07175384],
       ...,
       [5.87093105, 3.26776733, 5.77376392, 4.83785905, 1.23505729],
       [2.58090789, 2.9717549 , 3.2056756 , 1.5668861 , 1.8344118 ],
       [2.10320685, 3.26454813, 2.65973007, 2.44223698, 4.29697168]])

In [106]:
(s.sum(axis=1) < 17).mean()

0.72479

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

- How likely is it that a food truck will show up sometime this week?

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?